packages:
  - examples

allowBuilds:
  esbuild: false
  simple-git-hooks: false

minimumReleaseAgeExclude:
  - tar@7.5.7
  - tar@7.5.3
  - tar@7.5.8
  - tar@7.5.10
  - tar@7.5.11
  - tar@7.5.4

overrides:
  tar@<7.5.7: ^7.5.7
  tar@<7.5.8: ^7.5.8
  tar@<=7.5.10: ^7.5.11
  tar@<=7.5.2: ^7.5.3
  tar@<=7.5.3: ^7.5.4
  tar@<=7.5.9: ^7.5.10
